server:
  port: 8080

spring:
  application:
    name: auths
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springsecuritydemo
    username: postgres
    password: gajah
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include=*:

tokopakita:
  app:
    jwtSecret: iniadalahstringrahasiayangtidakbolehdiketahuiolehorangsembarangan
    jwtExpirationMs : 500000000